
server:
  port: 0

spring:
  datasource:
    url: jdbc:${DB_DIALECT}://${DB_HOST}:${DB_PORT}/stackoverflow_lite2
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: user-service

logging:
  level:
    org.springframework.security: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
    register-with-eureka: true
  fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://localhost:9411

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-size: 5
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        wait-duration-in-open-state: 3s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      user-service:
        timeout-duration: 3s
  retry:
    instances:
      user-service:
        max-attempts: 3
        wait-duration: 3s






